/**
 * AUTHENTICATION TYPES
 */

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

export const LOAD_CONTACT = "LOAD_CONTACT";
export const LOAD_CONTACT_SUCCESS = "LOAD_CONTACT_SUCCESS";
export const LOAD_CONTACT_FAILED = "LOAD_CONTACT_FAILED";

export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED";

export const SELECT_CONTACT = "SELECT_CONTACT";
export const SELECT_CHAT = "SELECT_CHAT"

export const SEND_NEW_MESSAGE = "SEND_NEW_MESSAGE";

export const RECEIVE_NEW_MESSAGE = "RECEIVE_NEW_MESSAGE";
